- name: Create  Config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml

- name: Create
  community.general.jenkins.job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.34.254:8080
    user: admin
    password: "{{jenkins_password}}"